services:
  mysql:
    container_name: mysql-sql-bsn
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATA: /var/lib/mysql/data
      MYSQL_DATABASE: book_social_bsn
    volumes:
      - mysql:/data/mysql
    ports:
      - 3307:3306  # Changed port to 3307:3306
    networks:
      - spring-projects
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-projects:
    driver: bridge
volumes:
  mysql:
    driver: local
